# Generated by Django 5.0.4 on 2026-05-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
